#!/usr/bin/env python3
"""
map.py - Render the PG search as a self-contained interactive HTML map.

Pure standard library at build time. The generated page loads Leaflet and
OpenStreetMap tiles from public CDNs when opened, so viewing it needs
internet - but no API key, ever.

Input: a JSON array of PG records, ideally the ranked output of
`rank.py --json` (so markers are colored by score), plus the zone JSON from
`geo.py zone` to draw the anchors and the search circle.

Usage:
  python rank.py --input pgs.json --zone zone.json --json \
      | python map.py --zone zone.json --title "PGs near HSR Layout" --open
  python map.py --input ranked.json --zone zone.json --output pg-map.html
"""
import argparse
import html
import json
import os
import sys
import webbrowser


def load(args):
    if args.input:
        with open(args.input, encoding="utf-8") as fh:
            return json.load(fh)
    return json.load(sys.stdin)


def esc(x):
    return html.escape(str(x)) if x is not None else ""


def score_color(score):
    if score is None:
        return "#9aa0a6"
    if score >= 75:
        return "#2e7d32"
    if score >= 55:
        return "#689f38"
    if score >= 35:
        return "#f9a825"
    return "#c0392b"


def popup_html(p, rank):
    name = esc(p.get("name") or "Unknown PG")
    url = p.get("url") or ""
    title = (f'<a href="{esc(url)}" target="_blank" rel="noopener">{name}</a>'
             if url.startswith("http") else name)
    bits = []
    if p.get("rent") is not None:
        cur = (p.get("currency") or "INR").upper()
        sym = {"INR": "&#8377;", "USD": "$", "EUR": "&euro;"}.get(cur, cur + " ")
        bits.append(f"<b>{sym}{p['rent']:,.0f}</b>/mo")
    for field in ("sharing", "gender", "food"):
        v = p.get(field)
        if v:
            bits.append(esc(", ".join(v) if isinstance(v, list) else v))
    ac = p.get("ac")
    if ac is not None:
        bits.append({True: "AC", False: "non-AC"}.get(ac, esc(ac)))
    line2 = " &middot; ".join(bits)
    extra = []
    if p.get("rating") is not None:
        extra.append(f"{p['rating']:.1f}&#9733; ({p.get('review_count') or 0} reviews)")
    if p.get("_dist_centroid_km") is not None:
        extra.append(f"{p['_dist_centroid_km']:g} km from centre")
    for label, km in (p.get("_dist_km") or {}).items():
        extra.append(f"{esc(label)}: {km:g} km")
    if p.get("source"):
        extra.append(esc(p["source"]))
    score = f" &middot; score {p['_score']:g}" if p.get("_score") is not None else ""
    return (f"<b>#{rank}</b> {title}{score}<br>{line2}<br>"
            + "<br>".join(extra))


TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>__TITLE__</title>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<style>
  :root { color-scheme: light dark; }
  html, body { height: 100%; margin: 0; }
  body { display: flex; flex-direction: column;
         font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
         background: #0f1115; color: #e8eaed; }
  header { padding: 14px 20px 12px; }
  h1 { font-size: 18px; margin: 0 0 4px; }
  .sub { color: #9aa0a6; font-size: 12.5px; display: flex; flex-wrap: wrap;
         gap: 12px; align-items: center; }
  .dot { display: inline-block; width: 10px; height: 10px; border-radius: 50%;
         margin-right: 4px; vertical-align: -1px; }
  #map { flex: 1; min-height: 0; }
  footer { padding: 8px 20px; color: #5f6368; font-size: 11.5px; }
  .leaflet-popup-content { font-size: 13px; line-height: 1.45; }
</style>
</head>
<body>
  <header>
    <h1>__TITLE__</h1>
    <div class="sub">
      <span>__SUBTITLE__</span>
      <span><span class="dot" style="background:#2e7d32"></span>75+</span>
      <span><span class="dot" style="background:#689f38"></span>55+</span>
      <span><span class="dot" style="background:#f9a825"></span>35+</span>
      <span><span class="dot" style="background:#c0392b"></span>&lt;35</span>
      <span><span class="dot" style="background:#8ab4f8"></span>anchors / zone</span>
    </div>
  </header>
  <div id="map"></div>
  <footer>Rents, availability, and ratings are a snapshot - always verify on a call or
  visit. Map data &copy; OpenStreetMap contributors. Generated by pg-finder.</footer>
  <script type="application/json" id="pg-data">__PAYLOAD__</script>
  <script>
    const data = JSON.parse(document.getElementById('pg-data').textContent);
    const map = L.map('map');
    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 19,
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);

    let fit = null;
    const extend = (lat, lon) => {
      if (fit) { fit.extend([lat, lon]); } else { fit = L.latLngBounds([lat, lon], [lat, lon]); }
    };

    if (data.zone) {
      const c = data.zone.centroid;
      const circle = L.circle([c.lat, c.lon], {
        radius: data.zone.radius_km * 1000,
        color: '#8ab4f8', weight: 2, dashArray: '6 6',
        fillColor: '#8ab4f8', fillOpacity: 0.06
      }).addTo(map).bindTooltip(data.zone.radius_km + ' km search zone');
      fit = circle.getBounds();
      L.circleMarker([c.lat, c.lon], {
        radius: 5, color: '#8ab4f8', fillColor: '#8ab4f8', fillOpacity: 1
      }).addTo(map).bindTooltip('Search centre');
      (data.zone.anchors || []).forEach(a => {
        L.marker([a.lat, a.lon]).addTo(map)
          .bindTooltip(a.label, { permanent: true, direction: 'top', offset: [-15, -12] })
          .bindPopup('<b>' + a.label + '</b><br>' + a.display_name);
        extend(a.lat, a.lon);
      });
    }

    data.pgs.forEach(p => {
      if (p.lat == null || p.lon == null) return;
      L.circleMarker([p.lat, p.lon], {
        radius: 9, color: '#0f1115', weight: 1.5,
        fillColor: p.color, fillOpacity: 0.92
      }).addTo(map).bindPopup(p.popup);
      extend(p.lat, p.lon);
    });

    if (fit) { map.fitBounds(fit.pad(0.12)); } else { map.setView([20.59, 78.96], 5); }
  </script>
</body>
</html>
"""


def main():
    ap = argparse.ArgumentParser(description="Render an interactive HTML map of PG candidates.")
    ap.add_argument("--input", help="PG/ranked JSON file (default: read stdin)")
    ap.add_argument("--zone", help="zone JSON from `geo.py zone` (draws anchors + circle)")
    ap.add_argument("--output", default="pg-map.html", help="HTML output path")
    ap.add_argument("--title", default="PG Search Map", help="page title / heading")
    ap.add_argument("--open", action="store_true", help="open the map in the default browser")
    args = ap.parse_args()

    pgs = load(args)
    if not isinstance(pgs, list):
        sys.exit("Input must be a JSON array of PG records.")

    zone = None
    if args.zone:
        with open(args.zone, encoding="utf-8") as fh:
            zone = json.load(fh)

    located, skipped = [], 0
    for rank, p in enumerate(pgs, 1):
        lat, lon = p.get("lat"), p.get("lon")
        if not isinstance(lat, (int, float)) or not isinstance(lon, (int, float)):
            skipped += 1
            continue
        located.append({"lat": lat, "lon": lon,
                        "color": score_color(p.get("_score")),
                        "popup": popup_html(p, rank)})

    subtitle = f"{len(located)} PGs mapped"
    if skipped:
        subtitle += f" ({skipped} without coordinates omitted)"
    if zone:
        subtitle += f" &middot; {zone['radius_km']:g} km radius"

    payload = json.dumps({"zone": zone, "pgs": located}, ensure_ascii=False)
    page = (TEMPLATE
            .replace("__TITLE__", esc(args.title))
            .replace("__SUBTITLE__", subtitle)
            .replace("__PAYLOAD__", payload.replace("</", "<\\/")))

    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write(page)
    abspath = os.path.abspath(args.output)
    print(f"Wrote {abspath} ({len(located)} PGs mapped, {skipped} skipped)")
    if args.open:
        webbrowser.open("file://" + abspath.replace(os.sep, "/"))


if __name__ == "__main__":
    main()
